/* Section: architecture evolution overview (v4 → v6, incl. minor versions).
   Placed first. Watch components enter/leave as you press Next:
   HARP leaves → PGD Proxy enters → Connection Manager + editions arrive. */
window.PGD_GROUPS = window.PGD_GROUPS || [];
window.PGD_GROUPS.push(
  { label:'Architecture evolution (4 → 6)', badge:'Overview', steps:[
    {t:'Architecture Overview: v4 → v6', tag:'new', chap:'Architecture evolution', sc:s_archoverview,
      rv:['v4','v5','v6','n'], fl:['a45','a56'],
      an:'One clubhouse, watched over three renovations: first by an outside receptionist, then a front desk built into the lobby, then a helper posted in every single room.',
      re:'A fast tour of the whole journey: in <b>v4</b>, an external <b>HARP</b> layer routes every connection to one lead master; in <b>v5</b>, HARP is removed and routing becomes the built-in <b>PGD Proxy</b>, driven by PGD\'s own Raft; in <b>v6</b>, routing moves onto <b>every data node</b> as the <b>Connection Manager</b>, with an HTTP API for automation. Same core engine throughout — only how you connect keeps getting simpler.',
      nr:'Here is a fast tour of the whole journey. In version four, an external HARP layer routes every connection to one lead master. In version five, HARP is removed and routing becomes the built-in PGD Proxy, driven by PGD\'s own Raft. In version six, routing moves onto every data node itself as the Connection Manager, with an HTTP API for automation. It is the same core engine throughout — only how you connect keeps getting simpler.',
      bv:[['bdr.node_summary','write_leader column across every version'],['bdr.group_raft_details','Raft state powering leader election from v5 onward']]},
    {t:'v4 — BDR + HARP', tag:'core', badge:'PGD 4', chap:'Architecture evolution', sc:s_arch_v4,
      rv:['app','proxy','dcs','mgr','lead','sh1','sh2','n'], fl:['a_ap','a_pl','a_md','a_ml'],
      an:'A separate receptionist desk (HARP) outside the building keeps a notepad of who is in charge and points every visitor to that one person.',
      re:'In <b>v4</b> the app reaches the database through <b>HARP</b> — an external layer with a <b>HARP Proxy</b> (router), a <b>HARP Manager</b> (holds the leader lease) and a <b>consensus store / DCS</b> (etcd or BDR native). One node is the writable <b>lead master</b>; the rest are discouraged "shadow" masters. Apps use a multi-host connection string.',
      nr:'In version four the app reaches the database through HARP, an external layer made of a HARP Proxy that routes traffic, a HARP Manager that holds the leader lease, and a consensus store, which is either etcd or BDR native. One node is the writable lead master, and the others are discouraged shadow masters. Apps connect with a multi-host connection string.',
      hb:'v4 docs · runbooks/4 · Always On Bronze / Silver / Gold / Platinum',
      cli:[{v:"harpctl v4",cmd:"harpctl get leader dc1",note:"who is lead master"},
           {v:"harpctl v4",cmd:"harpctl promote <node>",note:"move the lead master"},
           {v:"pgd v4",cmd:"pgd show-nodes",note:"inspect topology"}]},
    {t:'v4.4 — stabilization line', tag:'core', badge:'PGD 4', chap:'Architecture evolution', sc:s_arch_v44,
      rv:['t','b1','b2','b3'], fl:[],
      an:'No new rooms are built — the building is just inspected and certified so it can later connect to the new wing.',
      re:'The <b>4.4.x</b> minor line adds <b>no new features</b>. <b>4.4.0</b> is a prerequisite for upgrading to <b>PGD 6.1+</b>; <b>4.4.1</b> is a prerequisite for <b>6.2+</b> and preserves <code>node_uuid</code>/<code>node_kind</code> when joining a mixed-version cluster. These are Extended-Life-Support, upgrade-path releases.',
      nr:'The four point four minor line adds no new features. Four point four point zero is a prerequisite for upgrading to PGD six point one or later. Four point four point one is a prerequisite for six point two and preserves the node identity when joining a mixed-version cluster. These are Extended Life Support, upgrade-path releases.',
      hb:'v4.4 release notes'},
    {t:'v5 — HARP out, PGD Proxy in', tag:'new', badge:'PGD 5', chap:'Architecture evolution', sc:s_arch_v5,
      rv:['app','harp','proxy','cli','raft','lead','f1','f2','n'], fl:['a_ap','a_pl','a_rl'],
      an:'The outside receptionist desk is demolished. A new front desk is built right inside the building, and it reads the in-house voting board to know who is in charge.',
      re:'<b>v5</b> removes <b>HARP</b> entirely. Routing becomes the built-in <b>PGD Proxy</b> (run in HA), driven by PGD’s own <b>Raft</b>, which elects a single <b>write leader</b>. v5 also introduces <b>pgd-cli</b>, and the concepts of <b>groups & subgroups</b> with global vs local routing.',
      nr:'Version five removes HARP entirely. Routing becomes the built-in PGD Proxy, run in high availability and driven by PGD’s own Raft, which elects a single write leader. Version five also introduces the pgd C-L-I, and the idea of groups and subgroups with global versus local routing.',
      hb:'v5 docs · runbooks/5',
      cli:[{v:"pgd-cli v5",cmd:"pgd show-proxies",note:"list proxies (5.6)"},
           {v:"pgd v6/v5.7",cmd:"pgd group <group> set-leader <node>",note:"switchover"},
           {v:"pgd-cli v5",cmd:"pgd raft show",note:"who leads consensus"}]},
    {t:'v5.6 → 5.9 — what changed', tag:'core', badge:'PGD 5', chap:'Architecture evolution', sc:s_arch_v5x,
      rv:['t','r1','r2','r3','r4','n'], fl:[],
      an:'The new front desk gets steady upgrades over four service visits — smarter tools, faster lines, and a sneak peek at the next big desk.',
      re:'Across the v5 minors: <b>5.6</b> adds commit-scope <b>DEGRADE ON</b> / <b>ORIGIN_GROUP</b> and streaming via the decoding worker; <b>5.7</b> brings the <b>redesigned noun-verb CLI</b>, <code>pgd assess</code> and <code>pgd node upgrade</code>; <b>5.8</b> improves CLI usability and adds <code>bdr.galloc_chunk_info()</code>; <b>5.9</b> enables <b>in-place upgrade to PGD 6</b> and <b>back-ports the Connection Manager</b>.',
      nr:'Across the version five minors: five point six adds commit-scope degrade-on and origin-group, plus streaming through the decoding worker. Five point seven brings the redesigned noun-verb C-L-I, plus the assess and node-upgrade commands. Five point eight improves C-L-I usability. Five point nine enables in-place upgrade to PGD six and back-ports the Connection Manager.',
      hb:'v5.6 / 5.7 / 5.8 / 5.9 release notes'},
    {t:'v6 — Connection Manager + editions', tag:'new', badge:'PGD 6', chap:'Architecture evolution', sc:s_arch_v6,
      rv:['app','ops','proxyold','cm','ports','lead','f1','f2','ess','exp','n'], fl:['a_ac','a_oc','a_cl'],
      an:'The separate front desk is absorbed into every room: each room can greet visitors, and a web hotline lets other gadgets ask "who is in charge?"',
      re:'<b>v6</b> replaces PGD Proxy with the built-in <b>Connection Manager</b> — a worker on <b>every data node</b> exposing <b>RW (6432)</b>, <b>RO (6433)</b> and an <b>HTTP API (6434)</b>. v6 also formalizes two editions: <b>PGD Essential</b> (simple; ≤4 data nodes, ≤2 groups, fixed commit-scope set) and <b>PGD Expanded</b> (full features, no limits). <i>(Essential/Expanded are the current names for what earlier material called PGD-S / PGD-X.)</i>',
      nr:'Version six replaces PGD Proxy with the built-in Connection Manager, a worker on every data node exposing a read-write port, a read-only port, and an H-T-T-P A-P-I. Version six also formalizes two editions: PGD Essential, which is simple with at most four data nodes and two groups, and PGD Expanded, which is full-featured with no limits. Essential and Expanded are the current names for what earlier material called PGD-S and PGD-X.',
      hb:'v6 docs · runbooks/6',
      cli:[{v:"pgd v6",cmd:"pgd cluster show --health",note:"routing & node health"},
           {v:"HTTP",cmd:"curl http://node:6434/node/is-read-write",note:"HTTP API"},
           {v:"SQL",cmd:"SELECT * FROM bdr.stat_connection_manager;",note:"connection totals"}]},
    {t:'v6.1 → 6.4 — what changed', tag:'core', badge:'PGD 6', chap:'Architecture evolution', sc:s_arch_v6x,
      rv:['t','r1','r2','r3','r4','n'], fl:[],
      an:'The in-room desks keep gaining skills each visit: locks, encryption hand-off, smarter elections, and finally doing two jobs at once safely.',
      re:'v6 minors: <b>6.1</b> adds CLI GUC get/update, view & part-node commands and the <b>Leader DDL Lock</b>; <b>6.2</b> adds <b>TDE migration</b> on upgrade and <b>LDAP auth</b> for Connection Manager; <b>6.3</b> runs Connection Manager on <b>subscriber-only nodes</b> and improves leader election; <b>6.4 (latest)</b> adds a configurable <b>apply-error policy</b>, <b>large-object replication</b>, and makes <b>parallel apply compatible with Quorum Commit</b>.',
      nr:'Version six minors: six point one adds C-L-I get and update of Postgres settings, view and part-node commands, and the leader D-D-L lock. Six point two adds T-D-E migration on upgrade and LDAP authentication for the Connection Manager. Six point three runs the Connection Manager on subscriber-only nodes and improves leader election. Six point four, the latest, adds a configurable apply-error policy, large-object replication, and makes parallel apply compatible with quorum commit.',
      hb:'v6.1 / 6.2 / 6.3 / 6.4 release notes · latest = 6.4.0'},
    {t:'Upgrade Paths & Breaking Changes (v4 → v6)', tag:'new', chap:'Architecture evolution', sc:s_upgradepaths, rv:['v4tov5','v5tov6','n'], fl:[],
      an:'Moving to a newer clubhouse layout means the old front desk gets torn out and a new one goes up — you follow the renovation in order, and there\'s no putting the old desk back.',
      re:'Upgrading <b>v4 → v5</b> removes HARP entirely — routing becomes the built-in PGD Proxy. Upgrading <b>v5 → v6</b> swaps PGD Proxy for the <b>Connection Manager</b>, and folds CAMO/sync/group commit into <b>commit scopes</b>. Since <b>5.7</b>, <code>pgd node upgrade</code> handles Postgres and the PGD extension together. There is <b>no downgrade path</b>.',
      nr:'Upgrading version four to version five removes HARP entirely; routing becomes the built-in PGD Proxy. Upgrading version five to version six swaps PGD Proxy for the Connection Manager, and folds CAMO, synchronous commit, and group commit into commit scopes. Since version five point seven, the pgd node upgrade command handles both Postgres and the PGD extension together. There is no downgrade path, so plan upgrades carefully.',
      hb:'v4/v5/v6 upgrade guides · pgd node upgrade reference',
      bv:[['bdr.node_summary','extension version string to confirm an upgrade completed'],['bdr.event_summary','audit trail of upgrade-related node state changes']]}
  ]}
);
