/* Section: foundations — edit this file to change ONLY this section. */
window.PGD_GROUPS = window.PGD_GROUPS || [];
window.PGD_GROUPS.push(
{ label:'Foundations', badge:'Foundations', steps:[
    {t:'What is PGD?', tag:'core', chap:'Foundations', sc:s_whatis, rv:['a','n1','n2','n3','note'], fl:['a1'],
      an:'Three friends each keep an identical notebook. Write in one and it appears in all three. Lose one? The others still have everything.',
      re:'<b>PGD</b> (EDB Postgres Distributed) runs <b>several full copies</b> of your database at once. Your app talks to one place; the data lives in many for safety and speed.',
      nr:'PGD runs several complete copies of your database at the same time. Your app talks to one address, while the data lives safely in many copies.',
      bv:[['bdr.node','all nodes known to this node'],['bdr.node_group','node group membership'],['bdr.node_summary','node status overview']]},
    {t:'The mesh', tag:'core', chap:'Foundations', sc:s_mesh, rv:['n1','n2','n3','ml'], fl:['l12','l23','l13'],
      an:'The friends constantly show each other their notebooks, so nobody is ever out of date.',
      re:'Copies are linked in a <b>mesh</b>: every copy talks to every other. A change anywhere spreads everywhere.',
      nr:'The copies are linked in a mesh, meaning every copy talks to every other copy. A change made anywhere spreads to all of them.',
      bv:[['bdr.node_slots','outgoing replication slot state per peer'],['bdr.subscription_summary','incoming replication status per peer'],['bdr.node_replication_rates','lag rates between nodes']]},
    {t:'Multi-master writes', tag:'core', chap:'Foundations', sc:s_multimaster, rv:['w1','w2','w3','mm'], fl:['m12','m21','m13','m23'],
      an:'Any friend can write in their own notebook and the others copy it down. It is not one boss writing while everyone copies.',
      re:'PGD is <b>multi-master</b>: you can write to <b>any</b> copy and it replicates to the rest, both ways. Great for spreading load and surviving failures.',
      nr:'PGD is multi-master. You can write to any copy, not just one. Each change flows out to the others in both directions.',
      bv:[['bdr.node_slots','confirms bidirectional slots exist per node'],['bdr.stat_activity','live write activity on each node'],['bdr.workers','apply worker processes handling incoming changes']]},
    {t:'The Core Mesh Protocol Under the Hood', tag:'new', chap:'Foundations', sc:s_meshinternals, rv:['wal','dec','bdr','n'], fl:['u1','u2','out'],
      an:'Inside the clubhouse, one shelf holds the master ledger, a scribe copies out just the changed lines, and a runner carries those pages to every other clubhouse.',
      re:'Inside every PGD node, a commit becomes a replicated change through three layers: <b>WAL Storage</b> durably records the write, the <b>Logical Decoder</b> reads the WAL and reconstructs row-level changes, and the <b>BDR Worker</b> packages and streams them outward to every subscribing peer.',
      nr:'Inside every PGD node, a commit becomes a replicated change through three layers. WAL Storage durably records the write first. The Logical Decoder reads the WAL and reconstructs row-level changes. The BDR Worker then packages and streams those changes outward to every subscribing peer.',
      bv:[['bdr.node_slots','outbound slot state driven by the BDR worker per peer'],['bdr.workers','shows the logical decoder and BDR worker processes']]},
    {t:'Regional mesh & partition tolerance', tag:'new', chap:'Foundations', sc:s_meshpartition,
      rv:['usEast','euWest','apSouth','n'], fl:['lUE','lUA','lEA'],
      an:'Three towns each keep a full copy of the notebook and message each other directly. If the road to one town washes out, the others keep writing and simply catch it up later.',
      re:'Every node in a PGD cluster can accept writes and replicates directly to every other node in a full mesh. If a link between two regions drops, the origin node <b>buffers</b> the outgoing changes rather than losing them, and <b>flushes</b> them once connectivity returns — the partitioned region catches up automatically.',
      nr:'Every node in a PGD cluster can accept writes and replicates directly to every other node in a full mesh. If a link between two regions drops, the origin node buffers the outgoing changes instead of losing them, and flushes them once connectivity returns, so the partitioned region catches up automatically.',
      bv:[['bdr.node_slots','replay_lag_bytes and slot state per peer — grows while a link is down'],['bdr.subscription_summary','per-subscription apply state, useful for watching a partitioned peer catch up'],['bdr.node_summary','node status overview across the mesh']]},
    {t:'Eventual consistency', tag:'core', chap:'Foundations', sc:s_eventual, rv:['e1','e2','et','en'], fl:['ef'],
      an:'When one friend writes, the others copy it a heartbeat later — so for a split second they differ, then match.',
      re:'Copies are updated a tiny moment apart, then become identical. This is <b>eventual consistency</b>: not instant everywhere, but quickly the same.',
      nr:'Copies update a tiny moment apart, then become identical. This is called eventual consistency: not instant everywhere, but quickly the same.',
      bv:[['bdr.node_replication_rates','replay lag bytes & catchup interval per peer'],['bdr.node_slots','replay_lsn and sent_lsn to measure how far behind each peer is'],['bdr.subscription_summary','per-subscription apply state']]},
    {t:'Row origin', tag:'core', chap:'Foundations', sc:s_roworigin, rv:['o1','o2','o3','on'], fl:['o12','o23'],
      an:'Each note remembers who first wrote it, so it is never passed back to the person who started it.',
      re:'Every change carries its <b>origin</b>. Copies use this to avoid sending a change back to where it began — no endless loops.',
      nr:'Every change remembers where it started. Copies use this origin to avoid sending a change back to its source, which prevents endless loops.',
      bv:[['bdr.node_slots','origin_node_id tracked per replication slot'],['bdr.node_slots','LSN progress per replication origin']]},
    {t:'Replication sets', tag:'core', chap:'Foundations', sc:s_repsets, rv:['all','set1','set2','n'], fl:['la','lb'],
      an:'You decide which notebooks get which pages. Some pages go to everyone; some stay local.',
      re:'<b>Replication sets</b> group tables together. Copies subscribe to the sets they need, so not everything has to go everywhere.',
      nr:'Replication sets are groups of tables. Each copy subscribes to the sets it needs, so not every table has to be copied everywhere.',
      bv:[['bdr.replication_sets','all defined replication sets'],['bdr.tables','table membership across replication sets'],['bdr.node_group_replication_sets','which sets each node group subscribes to']]},
    {t:'Row filters', tag:'core', chap:'Foundations', sc:s_rowfilter, rv:['src','f','dst','n'], fl:['a','b'],
      an:'A gatekeeper only lets through the pages about, say, Europe — the rest stay behind.',
      re:'A <b>row filter</b> replicates only the rows matching a rule (e.g. region = EU), so a copy can hold just the slice it cares about.',
      nr:'A row filter only replicates rows that match a rule, such as region equals Europe. This lets a copy hold just the slice of data it needs.',
      bv:[['bdr.tables','row_filter column shows the filter expression per table/set'],['bdr.replication_sets','replication set definitions']]},
    {t:'DDL filters', tag:'core', chap:'Foundations', sc:s_ddlfilter, rv:['src','f','dst','n'], fl:['a','b'],
      an:'A second gatekeeper decides which "change the shape of things" instructions are allowed to travel.',
      re:'<b>DDL filters</b> control which <b>structure changes</b> (creating or altering tables) replicate, and where. DDL means data-definition language.',
      nr:'A DDL filter controls which structure changes, like creating or altering tables, are allowed to replicate and to where.',
      bv:[['bdr.replication_sets','DDL filter rules per replication set'],['bdr.event_summary','historical record of replicated DDL statements']]},
    {t:'Apply delay', tag:'core', chap:'Foundations', sc:s_applydelay, rv:['lead','clock','foll','n'], fl:['a','b'],
      an:'One friend deliberately waits a few seconds before copying — so if a mistake is made, there is time to catch it.',
      re:'<b>Apply delay</b> makes a copy intentionally lag. It acts like a time machine: if a bad change happens, you can read the delayed copy before the mistake lands.',
      nr:'Apply delay makes a copy wait on purpose before applying changes. It works like a time machine, giving you a chance to recover from a bad change before it lands.',
      bv:[['bdr.node_config_summary','apply_delay setting per node'],['bdr.subscription_summary','current apply state and lag per subscription']]},
    {t:'Replica Identity (RIF)', tag:'new', chap:'Foundations', sc:s_replicaidentity, rv:['haspk','nopk','n'], fl:[],
      an:'A note that says "change the third page" is useless if every page looks the same — you need a page number to know exactly which one.',
      re:'<b>Replica Identity</b> (RIF) tells a peer how to find the exact row an UPDATE or DELETE targets — normally its <b>primary key</b>. Without one, the row can\'t be uniquely matched and the change may be rejected. <code>bdr.default_replica_identity</code> sets the default for new tables, and v6 changes that default.',
      nr:'Replica identity tells a peer how to find the exact row an update or delete targets, normally using its primary key. Without one, the row can\'t be uniquely matched, and the change may be rejected. The setting bdr.default_replica_identity controls the default for new tables, and version six changes that default.',
      bv:[['bdr.tables','replication set membership and settings per table'],['bdr.node_config_summary','default_replica_identity setting for the node']]},
    {t:'Replication Slots & the PGD Group Slot', tag:'new', chap:'Foundations', sc:s_replicationslots, rv:['slotb','slotc','n'], fl:[],
      an:'Each friend has their own bookmark showing how far they have read, plus a shared bookmark that never moves past whoever is slowest — so nobody\'s pages get thrown away too early.',
      re:'Every peer gets its own <b>replication slot</b> tracking exactly what it still needs from this node. PGD also keeps a special <b>Group Slot</b> that always trails the slowest peer, so the origin node retains WAL until the whole group has caught up. Safe by design — but if <b>Raft stalls</b>, the Group Slot can\'t advance either, and retained WAL keeps growing until disk fills.',
      nr:'Every peer gets its own replication slot, tracking exactly what it still needs. PGD also keeps a special Group Slot that always trails the slowest peer, so the origin node retains write-ahead log data until the whole group has caught up. That\'s safe by design, but if Raft itself stalls, the Group Slot can\'t advance either, and retained log data keeps growing until disk fills.',
      bv:[['bdr.node_slots','per-peer slot state, plus the always-inactive group slot'],['bdr.node_replication_rates','lag per peer, used to spot which peer the group slot is pinned to']]},
    {t:'DDL Replication Mechanics & Table Rewrites', tag:'new', chap:'Foundations', sc:s_ddlmechanics, rv:['repl','local','rewrite','n'], fl:[],
      an:'Rewriting the shape of the shared notebook — like adding a new column of boxes — has to travel to everyone. But a few instructions, like "tidy your own desk," only make sense locally.',
      re:'Most DDL — <b>CREATE TABLE</b>, <b>ALTER TABLE ADD COLUMN</b> — replicates automatically. A few operations stay <b>local only</b>: <b>LOCK</b>, <b>VACUUM</b>, <b>ANALYZE</b>, and <b>CLUSTER</b> never replicate. Operations that <b>rewrite the table\'s data file</b>, like changing a column\'s type, take a cluster-wide lock — except <b>CREATE/DROP INDEX CONCURRENTLY</b>, built to avoid blocking.',
      nr:'Most schema changes, like creating a table or adding a column, replicate automatically to every node. A few operations stay local only: lock, vacuum, analyze, and cluster never replicate. Operations that rewrite the table\'s underlying data file, like changing a column\'s type, take a cluster-wide lock, except create or drop index concurrently, which is built to avoid blocking.',
      bv:[['bdr.event_summary','historical record of replicated DDL statements'],['bdr.global_locks','DDL lock acquired during a table-rewrite ALTER TABLE']]},
    {t:'Node Types: Physical Standby, Logical Standby & Subscriber-Only', tag:'new', chap:'Foundations', sc:s_nodetypes, rv:['phys','logi','sub','n'], fl:[],
      an:'A photocopy of one specific notebook, a friend who reads along and could take over, and a silent listener who just wants to read but never gets a vote.',
      re:'Beyond regular data nodes: a <b>Physical Standby</b> is a plain Postgres streaming copy of one specific node — doesn\'t vote, promotable, deprecated in v6. A <b>Logical Standby</b> receives logical changes and can be promoted to a full data node, though siblings can\'t simply follow it afterward. A <b>Subscriber-only</b> node receives every change for read scaling, but never votes and never publishes back.',
      nr:'Beyond regular data nodes, PGD supports three more node types. A physical standby is a plain Postgres streaming copy of one specific node. It doesn\'t vote, but can be promoted to replace that exact node, and is deprecated starting in version six. A logical standby receives logical changes and can be promoted to a full data node, though sibling standbys can\'t simply follow it afterward. A subscriber-only node receives every change for read scaling, but never votes and never publishes changes back.',
      bv:[['bdr.node_summary','node_kind_name distinguishes data, standby, and subscriber-only nodes'],['bdr.node_group_summary','group membership showing which nodes are subscriber-only']]},
    {t:'Clock Skew & Cluster Sizing Limits', tag:'new', chap:'Foundations', sc:s_clockskew, rv:['sync','drift','size'], fl:[],
      an:'If everyone\'s wristwatch agrees, "who wrote last" is a fair question. If one watch runs fast, that answer stops meaning anything.',
      re:'PGD relies on <b>synchronized clocks</b> across every node, monitored against <code>bdr.maximum_clock_skew</code>. A node whose clock drifts past that threshold makes <b>timestamp-based conflict resolution</b> unreliable. On sizing: typical clusters run <b>3–16 nodes</b>, and PGD has been tested well beyond that, into the hundreds.',
      nr:'PGD relies on synchronized clocks across every node, monitored against a maximum clock skew setting. A node whose clock drifts past that threshold makes timestamp-based conflict resolution unreliable. On sizing, typical clusters run three to sixteen nodes, and PGD has been tested well beyond that, into the hundreds of nodes.',
      bv:[['bdr.node_summary','node status overview, useful when checking per-node health'],['bdr.group_raft_details','Raft health, sensitive to clock drift beyond the configured skew limit']]},
  ]}
);
