/* Section: conflicts — edit this file to change ONLY this section. */
window.PGD_GROUPS = window.PGD_GROUPS || [];
window.PGD_GROUPS.push(
{ label:'Conflicts & data safety', badge:'Foundations', steps:[
    {t:'What is a conflict?', tag:'core', chap:'Conflicts & data safety', sc:s_conflict, rv:['a','b','clash','n'], fl:['a2','b2'],
      an:'Two friends edit the exact same line at the same moment, writing different things. Who is right?',
      re:'A <b>conflict</b> happens when two copies change the same row at the same time. Because anyone can write, PGD must detect and settle these.',
      nr:'A conflict happens when two copies change the same row at the same time. Because anyone can write in PGD, it must detect and settle these clashes.',
      bv:[['bdr.conflict_history','log of past conflicts (when logging enabled)'],['bdr.node_conflict_resolvers','current resolver rules per conflict type']]},
    {t:'Conflict resolution', tag:'core', chap:'Conflicts & data safety', sc:s_conflictres, rv:['a','b','judge','win','n'], fl:['a2','b2','w'],
      an:'A simple rule settles it: whoever wrote last wins, and everyone agrees to that.',
      re:'<b>Conflict resolution</b> applies a rule automatically. The default is "last update wins", so all copies end up agreeing without a human stepping in.',
      nr:'Conflict resolution applies a rule automatically. The default is last update wins, so all copies end up agreeing without anyone stepping in.',
      bv:[['bdr.node_conflict_resolvers','configured resolver per conflict type'],['bdr.conflict_history','past conflict outcomes'],['bdr.node_conflict_resolvers','conflict logging configuration']]},
    {t:'CRDTs', tag:'core', chap:'Conflicts & data safety', sc:s_crdt, rv:['a','b','sum','n'], fl:['a2','b2'],
      an:'For counters like "likes", you do not pick a winner — you add both. Five likes here plus three there equals eight.',
      re:'<b>CRDTs</b> (conflict-free replicated data types) are special values that <b>merge</b> instead of conflicting. Both changes count; no winner needed.',
      nr:'CRDTs, or conflict-free replicated data types, are special values that merge instead of clashing. Both changes are counted, so no winner is needed.',
      bv:[['bdr.sequences','galloc sequence allocation details'],['bdr.sequences','all sequences including CRDT-backed ones']]},
    {t:'Global locks', tag:'core', chap:'Conflicts & data safety', sc:s_globallock, rv:['a','lock','n1','n2','n'], fl:['d','l1','l2'],
      an:'Before rearranging the shared bookshelf, you ask everyone to pause so two people do not move it at once.',
      re:'<b>Global locks</b> coordinate big changes (like altering a table) across all copies, so two structure changes cannot clash.',
      nr:'A global lock coordinates big changes, like altering a table, across all copies at once, so two structure changes cannot clash.',
      bv:[['bdr.global_locks','active global DDL and DML locks with acquire stage and timing']]},
    {t:'Global advisory locks', tag:'core', chap:'Conflicts & data safety', sc:s_advisory, rv:['a','tok','b','n'], fl:['g','w'],
      an:'An app grabs a "do not disturb" ticket that every copy honours, so two apps do not do the same job at once.',
      re:'A <b>global advisory lock</b> is an app-chosen, cluster-wide ticket. The database does not force it; cooperating apps use it to coordinate work.',
      nr:'A global advisory lock is an app-chosen ticket that every copy respects. It lets cooperating apps coordinate work across the whole cluster.',
      bv:[['bdr.global_locks','shows advisory locks — relation column holds the lock key integers']]},
    {t:'Replication lag', tag:'core', chap:'Conflicts & data safety', sc:s_replag, rv:['fast','slow','gap','n'], fl:['f'],
      an:'If one friend writes faster than another can copy, a gap opens up. A big gap is risky.',
      re:'<b>Replication lag</b> is how far behind a copy is. Small lag is healthy; large lag risks losing recent writes if that copy is promoted after a failure.',
      nr:'Replication lag is how far behind a copy is. A small gap is healthy, but a large gap risks losing recent writes if that copy is promoted after a failure.',
      bv:[['bdr.node_slots','replay_lag_bytes and replay_lag_size per peer'],['bdr.node_replication_rates','catchup_interval per peer'],['bdr.subscription_summary','incoming lag per subscription']]},
    {t:'Local Locks & Blocking Replication', tag:'new', chap:'Conflicts & data safety', sc:s_locallocks, rv:['local','apply','n'], fl:[],
      an:'One friend leaves a page held open with their finger while they think — nobody else, including the copier, can touch that page until they let go.',
      re:'A <b>local</b> lock (row-level, explicit, or advisory) held by an ordinary transaction on a node can <b>block the apply worker</b> replicating an incoming change for that same row, stalling replication on that node until the lock releases. <code>pg_blocking_pids()</code> on the stuck backend finds the culprit.',
      nr:'A local lock held by an ordinary transaction on a node can block the apply worker replicating an incoming change for that same row, stalling replication on that node until the lock releases. Running pg_blocking_pids on the stuck backend finds exactly who is holding it.',
      bv:[['bdr.workers','apply worker processes and their current wait state'],['bdr.stat_activity','live activity, useful alongside pg_blocking_pids to find the blocker']]},
    {t:'Global Lock Modes: DDL → DML → Leader Lock', tag:'new', chap:'Conflicts & data safety', sc:s_globallockmodes, rv:['ddl','dml','leader','n'], fl:[],
      an:'Early on, rearranging one shelf meant asking the whole building to freeze. Later, only the room with that shelf pauses. Now, just the one person in charge of that shelf handles it.',
      re:'The <code>ddl_locking</code> setting has evolved: <b>on</b> (v4/v5 default) blocks every write, on every table, cluster-wide, during a schema change. <b>dml</b> narrows that to just the table being altered. v6\'s <b>leader</b> mode has only the <b>write leader</b> coordinate, keeping the rest of the cluster available.',
      nr:'PGD\'s ddl_locking setting has evolved across versions. On, the version four and five default, blocks every write, on every table, cluster-wide, for the duration of a schema change. The dml mode narrows that to just the table being altered. Version six\'s leader lock mode has only the write leader coordinate, keeping the rest of the cluster available.',
      bv:[['bdr.global_locks','active global DDL/DML locks with acquire stage and timing'],['bdr.node_config_summary','ddl_locking setting per node']]},
    {t:'Column-Level Conflict Resolution', tag:'new', chap:'Conflicts & data safety', sc:s_columnconflict, rv:['row','col','n'], fl:[],
      an:'Instead of tearing out and replacing a whole page because two people edited it, you keep each person\'s own line and merge them onto one page.',
      re:'By default, a conflict resolves at the <b>row level</b>: one whole version wins, even if it means losing a non-conflicting change to a different column. <b>Column-level conflict resolution</b> tracks a timestamp per column via <code>bdr.column_timestamps</code>, so two concurrent edits to different columns on the same row can <b>both</b> survive.',
      nr:'By default, a conflict resolves at the row level. One whole version wins, even if it means losing a non-conflicting change to a different column. Column-level conflict resolution tracks a timestamp for each column separately, so two concurrent edits to different columns on the same row can both survive.',
      bv:[['bdr.tables','column-level conflict resolution settings per table'],['bdr.conflict_history','logged conflicts, including which resolution strategy applied']]},
    {t:'Stream Triggers (Conflict & Transform)', tag:'new', chap:'Conflicts & data safety', sc:s_streamtriggers, rv:['conflict','transform','n'], fl:[],
      an:'One helper is trained to make the judgment call when two notes disagree; another quietly rewrites an incoming note so it fits the current notebook layout.',
      re:'<b>Stream triggers</b> run during apply. A <b>Conflict Trigger</b> swaps in custom logic in place of the default resolver — e.g. "trusted source always wins." A <b>Transform Trigger</b> reshapes an incoming row to match the table\'s current schema, useful for bridging schemas during a <b>rolling upgrade</b>.',
      nr:'Stream triggers run during apply. A Conflict Trigger swaps in your own custom logic in place of the default resolver, for example always trusting one source. A Transform Trigger reshapes an incoming row to match the table\'s current schema, which is useful for bridging old and new schemas during a rolling upgrade.',
      bv:[['bdr.triggers','conflict and transform stream triggers registered per table'],['bdr.conflict_history','logged conflicts, including custom-trigger resolutions']]},
  ]}
);
