/* Section: v5 — edit this file to change ONLY this section. */
window.PGD_GROUPS = window.PGD_GROUPS || [];
window.PGD_GROUPS.push(
{ label:'Version 5 · PGD + Proxy', badge:'PGD 5', steps:[
    {t:'PGD 5 Architecture', tag:'new', chap:'Version 5', sc:s_pgd5arch, rv:['single','multi','n'], fl:[],
      an:'One clubhouse building block that you can repeat: a single meeting room, or two meeting rooms in different towns with a referee posted in a third town just to keep the vote fair.',
      re:'PGD 5 offers two building blocks. <b>Single-location</b>: the basic 3-node group (3 data, or 2 data + witness), each node running its own <b>PGD Proxy</b>. <b>Multi-location</b>: that pattern repeated across 2 locations (6 nodes total), plus a <b>witness-only 3rd location</b> so global Raft survives losing an entire site.',
      nr:'PGD 5 offers two building blocks. A single location runs the basic 3-node group, each node running its own PGD Proxy. Multi-location repeats that across two locations, six nodes total, plus a witness-only third location so global Raft survives losing an entire site.',
      hb:'v5 docs · Always-on Single / Multi-location architectures',
      bv:[['bdr.node_group_summary','group layout per location'],['bdr.group_raft_details','per-group and global Raft status across locations']]},
    {t:'Rename to PGD', tag:'new', chap:'Version 5', sc:s_bdr, rv:['old','arr','new','n'], fl:['x'],
      an:'Same notebooks, tidier name and smoother tools.',
      re:'v5 renames <b>BDR → PGD</b>. The core idea is unchanged; management gets simpler and more unified.',
      nr:'Version 5 renames the technology from BDR to PGD. The core idea is unchanged, but management becomes simpler and more unified.',
      bv:[['bdr.node_summary','confirms installed PGD extension version'],['bdr.node_summary','node overview under the new PGD branding']]},
    {t:'PGD Proxy replaces HARP', tag:'new', chap:'Version 5', sc:s_proxy, rv:['app','proxy','cli','l1','l2','l3'], fl:['a','w','r12','r13','cliw'],
      an:'The outside receptionist is gone; the front desk is now built into the building, with one remote control to run it.',
      re:'HARP is removed. <b>PGD Proxy</b> is the built-in routing layer, tracking the leader via PGD\'s own Raft. v5 also adds <b>pgd-cli</b>, one tool to manage the cluster.',
      nr:'HARP is removed. The built-in PGD Proxy now routes traffic using PGD\'s own Raft. Version 5 also adds pgd C-L-I, a single tool to manage the whole cluster.',
      bv:[['bdr.node_summary','write_leader used by PGD Proxy for routing decisions'],['bdr.group_raft_details','Raft state powering PGD Proxy leader tracking']]},
    {t:'Switchover & failover', tag:'new', chap:'Version 5', sc:s_failover, rv:['proxy','old','new','f3','x','n'], fl:['toold','tonew','rep'],
      an:'If the decider goes home sick, the group instantly picks a new one — and visitors never notice.',
      re:'<b>Failover</b> is automatic when a leader fails; <b>switchover</b> is the same move done on purpose. Either way your app keeps the same address.',
      nr:'Failover happens automatically when a leader fails. Switchover is the same move done on purpose. Either way, your app keeps using the same address.',
      bv:[['bdr.event_summary','records every leader election and node state transition'],['bdr.node_summary','current write_leader after failover']]},
    {t:'Maintenance mode', tag:'new', chap:'Version 5', sc:s_maint, rv:['n1','n2','n3','n'], fl:['m1'],
      an:'Send one friend on a break to fix their pen, while the others keep taking notes.',
      re:'<b>pgd_maintenance</b> safely takes a node offline for patching while the rest of the cluster keeps serving, then brings it back.',
      nr:'Maintenance mode safely takes one node offline for patching while the rest of the cluster keeps serving, then brings it back in.',
      bv:[['bdr.node_summary','node_state shows "maintenance" during maintenance window'],['bdr.event_summary','audit trail of maintenance state changes']]},
    {t:'Replication lag control', tag:'new', chap:'Version 5', sc:s_lagctl, rv:['fast','slow','g','brake','n'], fl:['flow','b'],
      an:'If one friend races ahead, they are gently asked to slow down so nobody falls behind.',
      re:'<b>Lag control</b> throttles the leader when a follower drifts too far behind, keeping copies close so a later failover loses little data.',
      nr:'Replication lag control gently slows the leader when a follower drifts too far behind, keeping copies close so a later failover loses very little data.',
      bv:[['bdr.node_replication_rates','catchup_interval and replay_lag_bytes per peer'],['bdr.node_replication_rates','lag control configuration and current throttle state']]},
    {t:'Raft per group', tag:'new', chap:'Version 5', sc:s_raftgroup, rv:['gA','gAt','a1','a2','a3','gB','gBt','b1','b2','b3','n'], fl:[],
      an:'Each city clubhouse can hold its own local vote, so one city keeps working even if it cannot reach another.',
      re:'v5 adds <b>per-group Raft</b>: each location/group can run its own consensus, improving multi-region resilience.',
      nr:'Version 5 adds per-group Raft, so each location can run its own local vote. This improves resilience when regions cannot reach each other.',
      bv:[['bdr.node_group','one row per node group — each has its own Raft instance'],['bdr.group_raft_details','Raft status per node group']]},
    {t:'Raft repair tools', tag:'new', chap:'Version 5', sc:s_raftfix, rv:['snap','reset','kv','n'], fl:[],
      an:'If the voting gets jammed, there are tools to reset it or restore it from a saved copy.',
      re:'v5 adds <b>snapshot export/import</b> and <b>reset</b> for Raft, plus a way to inspect the KV store — recovery tools when consensus gets stuck.',
      nr:'Version 5 adds tools to export, import, or reset Raft consensus, plus a way to inspect the key-value store. These help recover the cluster if voting ever gets stuck.',
      bv:[['bdr.group_raft_details','current Raft state to check if repair is needed'],['bdr.event_summary','state history to diagnose stuck consensus']]},
    {t:'Logical-join upgrades', tag:'new', chap:'Version 5', sc:s_upgrade, rv:['oldc','join','newc','n'], fl:['a','b'],
      an:'Build a brand-new clubhouse, let it quietly copy everything from the old one, then move in — with barely a pause.',
      re:'<b>Logical-join upgrade</b>: new nodes join and sync live from the old cluster, then you switch over — upgrading across major versions with minimal downtime.',
      nr:'A logical-join upgrade lets new nodes join and sync live from the old cluster, then you switch over. This upgrades across major versions with very little downtime.',
      bv:[['bdr.node_summary','node_state shows "joining" / "active" during live sync'],['bdr.node_catchup_info','data catchup progress during logical join'],['bdr.subscription_summary','subscription state per joining node']]},
    {t:'Zero-downtime rolling upgrade', tag:'new', chap:'Version 5', sc:s_rollingupgrade, rv:['c1','c2','c3','n'], fl:['l12','l23'],
      an:'One clubhouse at a time is roped off, quietly refitted, and reopened before the next one closes — the group never stops meeting.',
      re:'A <b>rolling upgrade</b> takes one node out of the replication path at a time, upgrades it, and rejoins it before moving to the next. The rest of the cluster keeps serving reads and writes throughout, so the whole cluster moves to a new major version with zero downtime.',
      nr:'A rolling upgrade takes one node out of the replication path at a time, upgrades it, and rejoins it before moving to the next. The rest of the cluster keeps serving reads and writes throughout, so the whole cluster moves to a new major version with zero downtime.',
      bv:[['bdr.node_summary','node_state shows a node mid-upgrade vs active'],['bdr.node_catchup_info','catch-up progress as an upgraded node rejoins'],['bdr.event_summary','audit trail of each node\'s join/part during the rolling upgrade']]},
  ]}
);
