/* Section: v6 — edit this file to change ONLY this section. */
window.PGD_GROUPS = window.PGD_GROUPS || [];
window.PGD_GROUPS.push(
{ label:'Version 6 · Editions & Commit scopes', badge:'PGD 6', steps:[
    {t:'PGD 6 Architecture', tag:'new', chap:'Version 6', sc:s_pgd6arch, rv:['single','two','read','n'], fl:[],
      an:'One clubhouse room versus two rooms in different towns each running their own meeting, versus one room with extra listeners posted outside who never get a vote.',
      re:'PGD 6 replaces named tiers with <b>deployment patterns</b>: <b>Single data group</b> — three data nodes forming one Raft group, the foundational lowest-cost pattern; <b>Two data groups</b> — one group per location, each with its own write leader, active-active across sites; and <b>Read scaling</b> — add <b>subscriber-only</b> nodes that receive every change but never vote or write, scaling reads without growing the mesh.',
      nr:'PGD 6 replaces named tiers with deployment patterns. A single data group is three data nodes forming one Raft group — the foundational, lowest-cost pattern. Two data groups puts one group per location, each with its own write leader, active-active across sites. Read scaling adds subscriber-only nodes that receive every change but never vote or write, scaling reads without growing the mesh.',
      hb:'v6 docs · deployment patterns: single data group, two data groups, read scaling',
      bv:[['bdr.node_group_summary','group type and topology per deployment pattern'],['bdr.node_summary','node_kind_name shows subscriber-only nodes in the read-scaling pattern']]},
    {t:'PGD-S vs PGD-X editions', tag:'new', chap:'Version 6', sc:s_editions, rv:['sbox','st','sd','s1','s2','s3','xbox','xt','xd','x1','x2','x3','x4','xw1','xw2','xb'], fl:[],
      an:'A small starter kit (one clubhouse, three notebooks) versus a big network across many cities with referees and a backup vault.',
      re:'v6 formalizes two editions: <b>PGD Essential</b> — a simple quick-start edition (capped at ≤4 data nodes, ≤2 groups, with a fixed set of commit scopes); and <b>PGD Expanded</b> — full features with no node/group limits, many data nodes across locations, plus witnesses and Barman backups. <i>(Essential/Expanded are the current doc names for what earlier material called "PGD-S / PGD-X".)</i>',
      nr:'Version 6 formalizes two editions. PGD Essential is a simple quick-start edition, capped at four data nodes, two groups, and a fixed set of commit scopes. PGD Expanded has full features with no limits: many data nodes across locations, plus witnesses and Barman backups. Essential and Expanded are the current names for what earlier material called PGD-S and PGD-X.',
      bv:[['bdr.node_group_summary','edition-level node group layout'],['bdr.node_summary','node_kind distinguishes data vs witness nodes per edition']]},
    {t:'Connection Manager', tag:'new', chap:'Version 6', sc:s_cm, rv:['app','ops','cm','l1','l2','l3'], fl:['a','api','w','r12','r13'],
      an:'The front desk gets an upgrade, and now other smart gadgets can phone it to ask "who is in charge?"',
      re:'v6 replaces PGD Proxy with the <b>Connection Manager</b>, a smarter routing layer. It adds an <b>HTTP API</b> so tools and automation can query it over the web.',
      nr:'Version 6 replaces PGD Proxy with the Connection Manager, a smarter routing layer. It adds an HTTP A-P-I so other tools and automation can query it over the web.',
      bv:[['bdr.stat_connection_manager','connection manager routing statistics (v6)'],['bdr.node_summary','write_leader used by Connection Manager for routing']]},
    {t:'Commit scopes', tag:'new', chap:'Version 6', sc:s_commitscope, rv:['hub','camo','sync','group','n'], fl:['c','s','g'],
      an:'Instead of three separate safety gadgets with their own buttons, there is now one settings menu where you choose how safe each write must be.',
      re:'<b>Commit scopes</b> are v6\'s big idea: the durability concepts you already met — <b>CAMO, synchronous commit and group commit</b> — are no longer separate mechanisms but <b>options you pick from one place</b>.',
      nr:'Commit scopes are version six\'s big idea. The durability concepts you already met, namely CAMO, synchronous commit, and group commit, are no longer separate mechanisms. They become options you choose from one place.',
      bv:[['bdr.commit_scopes','all defined commit scope rules'],['bdr.stat_commit_scope','per-scope commit count, errors and latency'],['bdr.stat_commit_scope','per-backend active commit scope usage']]},
    {t:'TDE encryption', tag:'new', chap:'Version 6', sc:s_tde, rv:['plain','key','disk','n'], fl:['a','b'],
      an:'Everything written to disk is scrambled with a secret key — a stolen disk is just gibberish.',
      re:'<b>TDE</b> (Transparent Data Encryption) automatically scrambles data on disk. v6 also supports rotating or migrating the encryption key.',
      nr:'TDE, or Transparent Data Encryption, automatically scrambles data on disk so a stolen disk is useless. Version 6 also supports rotating or migrating the encryption key.',
      bv:[['bdr.node_config_summary','tde_enabled flag per node config']]},
    {t:'Automatic reconciliation', tag:'new', chap:'Version 6', sc:s_reconcile, rv:['a','b','fix','n'], fl:['d','to'],
      an:'If one notebook is missing a line the others have, the group quietly fills it back in.',
      re:'<b>Automatic reconciliation</b> detects small differences between copies and heals them on its own, keeping all copies identical without manual fixes.',
      nr:'Automatic reconciliation detects small differences between copies and heals them on its own, keeping all copies identical without anyone fixing them by hand.',
      bv:[['bdr.taskmgr_work_queue','reconciliation work items created and tracked per node'],['bdr.taskmgr_work_queue','locally managed reconciliation tasks']]},
    {t:'Optimized mesh', tag:'new', chap:'Version 6', sc:s_optmesh, rv:['full','opt','arr','n'], fl:[],
      an:'In a huge group, having everyone message everyone is too noisy — so they connect more cleverly.',
      re:'As clusters grow, a full mesh gets expensive. <b>Optimized mesh</b> trims connections intelligently while still moving data everywhere it needs to go.',
      nr:'As clusters grow, connecting every node to every other gets expensive. Optimized mesh trims those connections intelligently while still moving data everywhere it is needed.',
      bv:[['bdr.node_slots','active slots show which connections currently exist in the mesh'],['bdr.subscription_summary','active subscriptions per peer after mesh optimisation']]},
    {t:'Lag history', tag:'new', chap:'Version 6', sc:s_laghistory, rv:['mon','n1','n2','n3','n'], fl:['m1','m2','m3'],
      an:'A logbook records how far behind each notebook has been over time, so problems are spotted early.',
      re:'<b>Lag history</b> keeps a timeline of replication health across nodes, so you can diagnose trends before they become outages.',
      nr:'Lag history keeps a timeline of replication health across nodes, so you can spot worrying trends before they turn into outages.',
      bv:[['bdr.node_replication_rates','time-series lag data per peer (v6)'],['bdr.node_replication_rates','current replay_lag_bytes and catchup_interval']]},
    {t:'Tuning conflicts', tag:'new', chap:'Version 6', sc:s_conflictcfg, rv:['log','res','n'], fl:[],
      an:'You can write down every disagreement for later review, and choose the rule used to settle them.',
      re:'v6 lets you turn on <b>conflict logging</b> (record every clash) and switch the <b>conflict resolver</b> strategy, including tricky multi-unique-key cases.',
      nr:'Version 6 lets you log every conflict for later review and switch the conflict resolver strategy, including tricky cases involving multiple unique keys.',
      bv:[['bdr.node_conflict_resolvers','conflict logging configuration per table/set'],['bdr.node_conflict_resolvers','current resolver per conflict type'],['bdr.conflict_history','full log of recorded conflicts']]},
    {t:'Parallel apply', tag:'core', chap:'Version 6', sc:s_parallel, rv:['lead','w1','w2','w3','n'], fl:['a','b','c'],
      an:'Several helpers copy incoming pages at once, so a busy writer never overwhelms them.',
      re:'<b>Parallel apply</b> lets a follower use several workers at once to keep up with a busy leader. It can be turned off when debugging.',
      nr:'Parallel apply lets a follower use several workers at once to keep up with a busy leader. It can be turned off when debugging an issue.',
      bv:[['bdr.workers','shows parallel apply worker processes and their states'],['bdr.stat_activity','live activity per apply worker process']]},
    {t:'Transaction streaming', tag:'core', chap:'Version 6', sc:s_streaming, rv:['big','stream','foll','n'], fl:['a','b'],
      an:'You start reading a long letter aloud as it is being written, instead of waiting for the very end.',
      re:'<b>Transaction streaming</b> sends a big transaction to copies while it is still being written, instead of waiting for commit — faster, with less lag.',
      nr:'Transaction streaming sends a big transaction to copies while it is still being written, instead of waiting for it to finish. This is faster and reduces lag.',
      bv:[['bdr.node_slots','streaming_state column shows if streaming is active per slot'],['bdr.subscription_summary','streaming status per incoming subscription']]},
    {t:'Single decoder worker', tag:'core', chap:'Version 6', sc:s_decoder, rv:['many','arr','one','n'], fl:['x'],
      an:'Instead of re-reading the same book once for each friend, one reader reads it aloud and everyone listens.',
      re:'A <b>single decoder worker</b> reads the change log once and fans it out to all peers, instead of decoding separately per peer — saving CPU on busy clusters.',
      nr:'A single decoder worker reads the change log once and shares it with all peers, instead of decoding separately for each one. This saves CPU on busy clusters.',
      bv:[['bdr.workers','decoder_worker process visible here'],['bdr.worker_tasks','tasks assigned to the single decoder worker']]},
    {t:'Node lifecycle', tag:'core', chap:'Version 6', sc:s_nodelifecycle, rv:['join','promote','part','n'], fl:[],
      an:'Friends can join the group and catch up, a stand-in can be promoted to replace someone, and a member who left is cleanly removed.',
      re:'PGD manages a node\'s whole life: <b>join</b> (add and sync), <b>promote</b> (a standby becomes a full node), and <b>part</b> (cleanly remove a dead node).',
      nr:'PGD manages a node\'s whole life: joining and syncing a new node, promoting a standby to replace a failed one, and parting, which cleanly removes a dead node.',
      bv:[['bdr.event_summary','full join/promote/part state history per node'],['bdr.node_catchup_info','catch-up progress during node join'],['bdr.node_summary','current state of all nodes']]},
    {t:'Safe housekeeping', tag:'core', chap:'Version 6', sc:s_indexvacuum, rv:['idx','vac','n'], fl:[],
      an:'Tidying the shared notebooks — adding a new index, reclaiming space — without making everyone stop work.',
      re:'v6 covers routine Postgres upkeep across copies: <b>CREATE INDEX CONCURRENTLY</b> (build indexes without blocking writes) and <b>VACUUM FULL</b> (reclaim space) done safely cluster-wide.',
      nr:'Version 6 covers routine Postgres upkeep across all copies, such as building indexes without blocking writes, and reclaiming space, all done safely across the cluster.',
      bv:[['bdr.global_locks','DDL lock acquired during CREATE INDEX CONCURRENTLY and VACUUM FULL'],['bdr.event_summary','records schema-level DDL operations across the cluster']]},
  ]}
);
