/* Section: troubleshooting & operations toolkit — edit this file to change ONLY this section. */
window.PGD_GROUPS = window.PGD_GROUPS || [];
window.PGD_GROUPS.push(
  { label:'Troubleshooting & Operations Toolkit', badge:'PGD 6', steps:[
    {t:'PGD Roles & Privilege Model', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      ref:[
        {label:'bdr_application', detail:'Day-to-day app access with narrow grants. What most application connections should use.'},
        {label:'bdr_read_all_stats', detail:'Read-only access to every statistics view — built for monitoring tools.'},
        {label:'bdr_read_all_conflicts', detail:'Read-only access to conflict history — built for monitoring and auditing.'},
        {label:'bdr_monitor', detail:'Bundles broader read access together, for operational dashboards.'},
        {label:'bdr_superuser', detail:'Full control over the extension. Grant it sparingly — not as an app\'s everyday role.'}
      ],
      an:'Instead of handing everyone the master key, you hand out the specific key that opens the door they actually need.',
      re:'PGD ships a ladder of predefined roles: <b>bdr_application</b> for day-to-day app access with narrow grants; <b>bdr_read_all_stats</b> and <b>bdr_read_all_conflicts</b> for read-only monitoring; <b>bdr_monitor</b> bundling broader read access for dashboards; and <b>bdr_superuser</b> for full control — grant it sparingly, not as the app\'s everyday role.',
      nr:'PGD ships a ladder of predefined roles. bdr_application is what most apps should use day to day, with narrow grants. bdr_read_all_stats and bdr_read_all_conflicts give read-only visibility for monitoring tools. bdr_monitor bundles broader read access for operational dashboards. bdr_superuser has full control, and should be granted sparingly rather than used as the app\'s everyday role.',
      bv:[['bdr.node_summary','safe to query with any read-only monitoring role'],['bdr.global_locks','requires broader visibility, typically via bdr_monitor']]},
    {t:'Rebuilding & Rejoining a Node', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      guideLabels:['Mechanism','Best for'],
      guide:[
        {symptom:'I want the simplest, most flexible rejoin',
          diagnose:'Logical Join re-syncs the node via logical replication.',
          fix:'Flexibility over speed — a good fit for smaller databases.'},
        {symptom:'My database is large and I need it fast',
          diagnose:'Physical Join byte-copies data with pg_basebackup, then converts it (1 or 2-step).',
          fix:'Large databases, where copying bytes beats re-decoding every change.'},
        {symptom:'I\'m on v6 and want the modern, unified path',
          diagnose:'pgd node setup unifies join and build into a single command.',
          fix:'Replacing the older bdr_init_physical on v6 clusters.'},
        {symptom:'I want the whole flow automated',
          diagnose:'TPA can manage the entire join or rebuild flow end-to-end.',
          fix:'Clusters already managed by TPA, where hands-off orchestration matters most.'}
      ],
      an:'A friend who has lost their notebook entirely can either copy every page by hand from a neighbor, or receive a photocopy of an existing notebook and just add the tabs.',
      re:'When a node needs to come back, PGD offers a few paths: <b>Logical Join</b> re-syncs it via logical replication (slower, flexible); <b>Physical Join</b> byte-copies data with <code>pg_basebackup</code> then converts it, in one or two steps (faster for large databases); v6\'s <b>pgd node setup</b> unifies this into one command, replacing <code>bdr_init_physical</code>; and <b>TPA</b> can manage the whole flow as automation.',
      nr:'When a node needs to come back, PGD offers a few paths. Logical Join re-syncs it through logical replication, which is slower but flexible. Physical Join byte-copies data with pg_basebackup and then converts it, in one or two steps, which is faster for large databases. Version six\'s pgd node setup unifies this into one command, replacing bdr_init_physical. And TPA can manage the whole join or rebuild flow end to end as automation.',
      hb:'v4/v5/v6 runbooks — physical join (1-step, 2-step), logical join, pgd node setup',
      bv:[['bdr.node_summary','node_state shows joining/catchup/active during a rejoin'],['bdr.node_catchup_info','catch-up progress while a rebuilt node syncs']]},
    {t:'LiveCompare — Divergence Detection', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      ref:[
        {label:'What it does', detail:'Scans both copies of a table, row by row, outside normal replication.'},
        {label:'What it finds', detail:'Silent divergence — rows that differ without ever being logged as a conflict.'},
        {label:'When to run it', detail:'After a resync or skip-changes operation, or on a regular schedule.'},
        {label:'--conflicts mode', detail:'Shows resolver history for rows that were previously logged as conflicts.'}
      ],
      an:'A separate auditor walks both notebooks side by side, page by page, and flags any line that quietly drifted apart — even if nobody ever wrote down a disagreement.',
      re:'<b>LiveCompare</b> scans both copies of a table, row by row, outside normal replication. It surfaces <b>silent divergence</b> — rows that differ without ever being logged as a conflict. Run it after a resync or <b>skip-changes</b> operation, or on a schedule, to catch drift early; its <code>--conflicts</code> mode shows resolver history.',
      nr:'LiveCompare scans both copies of a table, row by row, outside normal replication. It surfaces silent divergence, meaning rows that differ without ever being logged as a conflict. Run it after a resync or a skip-changes operation, or on a regular schedule, to catch drift early, and use its conflicts mode to see resolver history.',
      hb:'LiveCompare docs · run after bdr.resynchronize_table_from_snapshot or skip-changes',
      bv:[['bdr.conflict_history','logged conflicts — LiveCompare finds drift that never appears here'],['bdr.tables','table metadata used to scope a LiveCompare run']]},
    {t:'PGD CLI Toolkit & Diagnostics', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      ref:[
        {label:'pgd cluster show', detail:'Overall cluster health and topology snapshot.'},
        {label:'pgd nodes list', detail:'Every node, its state, and its role.'},
        {label:'pgd raft show', detail:'Who currently leads consensus.'},
        {label:'pgd replication show', detail:'Lag and slot status per peer.'},
        {label:'pgd events show', detail:'The audit trail of every state change.'},
        {label:'harpctl / bdr-cli', detail:'Older commands — map onto this same pgd-cli starting in version five.'}
      ],
      an:'One dashboard with five gauges, instead of five separate old tools you had to remember individually.',
      re:'The <b>pgd</b> CLI covers most diagnostics in one place: <code>pgd cluster show</code> (health & topology), <code>pgd nodes list</code> (state & role per node), <code>pgd raft show</code> (who leads consensus), <code>pgd replication show</code> (lag & slot status), and <code>pgd events show</code> (the audit trail). Older <code>harpctl</code> / <code>bdr-cli</code> commands map onto <code>pgd-cli</code> from v5 onward.',
      nr:'The pgd command line toolkit covers most diagnostics in one place. Pgd cluster show gives an overall health and topology snapshot. Pgd nodes list shows every node, its state, and its role. Pgd raft show reveals who currently leads consensus. Pgd replication show reports lag and slot status per peer. And pgd events show is the audit trail of every state change. Older harpctl and bdr C-L-I commands map onto this same pgd C-L-I starting in version five.',
      hb:'pgd-cli v5/v6 command reference',
      bv:[['bdr.node_summary','backs pgd cluster show / pgd nodes list'],['bdr.group_raft_details','backs pgd raft show'],['bdr.event_summary','backs pgd events show']]},
    {t:'Common Troubleshooting Playbooks', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      guide:[
        {symptom:'Node C is unreachable',
          diagnose:'Check bdr.node_summary for its state — is it actually down, or just slow to respond?',
          fix:'Restart the node if it\'s simply offline. If it needs a full rebuild, part it and rejoin it.'},
        {symptom:'The apply worker keeps crash-looping',
          diagnose:'Check bdr.event_summary — it usually shows a DDL/DML collision behind the crash.',
          fix:'Skip the offending LSN, or resynchronize the affected table, then let replication resume.'},
        {symptom:'One peer falls behind and the gap keeps growing',
          diagnose:'Check bdr.node_replication_rates and bdr.node_slots for replay lag — a missing primary key or index often causes a sequential scan on apply.',
          fix:'Add the missing index if that\'s the cause, or use replication lag control to throttle the leader until the peer catches up.'},
        {symptom:'No write leader gets elected',
          diagnose:'Check bdr.group_raft_details for quorum — a split cluster or too few voters can block an election.',
          fix:'Restore quorum by bringing nodes back online or adding a witness. Reset Raft only if it\'s genuinely stuck.'},
        {symptom:'The Connection Manager can\'t find a leader',
          diagnose:'Check its HTTP API and bdr.stat_connection_manager — is routing actually down, or is the app using a stale address?',
          fix:'Fail over manually if routing is confirmed down, and confirm the app is pointed at the Connection Manager, not a cached address.'}
      ],
      an:'A pocket guide at the front desk: find the symptom that matches what you\'re seeing, and flip it open for the check and the fix.',
      re:'Click a symptom below to reveal how to diagnose it and the recommended fix — a quick-reference guide for the most common PGD problems.',
      nr:'Here are five common troubleshooting playbooks. Click any symptom to reveal how to diagnose it and the recommended fix.',
      bv:[['bdr.node_summary','node state — the first check for a down node'],['bdr.event_summary','surfaces DDL/DML collisions behind broken replication'],['bdr.node_replication_rates','replay lag per peer — the first check when one peer falls behind'],['bdr.group_raft_details','quorum status when no write leader is elected']]},
    {t:'Real-World Failure Patterns', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      guide:[
        {symptom:'Repeated Raft elections under load',
          diagnose:'Too many concurrent candidates call elections around the same time — sometimes called the "birthday paradox" crash.',
          fix:'Stagger the election timeout jitter so elections don\'t collide as often.'},
        {symptom:'One peer keeps falling further behind',
          diagnose:'A missing primary key or unique index forces a sequential scan during apply.',
          fix:'Add the missing index, then let the peer catch up.'},
        {symptom:'Grants vanished on one node after a restore',
          diagnose:'Roles are cluster-global objects, not per-database — a restore can miss them.',
          fix:'Check bdr.role_replication and replicate roles explicitly.'},
        {symptom:'Writes stopped everywhere after a data center outage',
          diagnose:'The data center that went down held the Raft majority.',
          fix:'Promote a witness manually to restore quorum, and review witness placement.'}
      ],
      an:'Four stories from other clubhouses that hit the same snag you might one day — so you recognize the symptom before it becomes a crisis.',
      re:'Patterns from real support cases: repeated <b>Raft elections</b> under load (stagger the election timeout jitter); <b>replay lag</b> from a missing primary key forcing a sequential scan; <b>grants broken</b> after a restore, because roles are <b>cluster-global</b> objects, not per-database; and <b>quorum lost</b> when a data center holding the Raft majority goes down.',
      nr:'A few patterns from real support cases. Repeated Raft elections under load, sometimes called the birthday-paradox crash, are fixed by staggering the election timeout jitter. One peer replaying far behind is often caused by a missing primary key forcing a sequential scan on apply, fixed by adding the index. Grants broken on one node after a restore usually trace back to roles being cluster-global objects, not per-database ones. And losing a data center that held the Raft majority stops writes everywhere, until a witness is promoted manually.',
      bv:[['bdr.group_raft_details','election frequency — watch for repeated elections under load'],['bdr.node_replication_rates','spot a peer replaying unusually slowly'],['bdr.role_replication','confirms whether a role is set to replicate cluster-wide']]},
    {t:'Securing Client Connections (TLS & Cert Rotation)', tag:'new', chap:'Troubleshooting & Operations Toolkit',
      ref:[
        {label:'TLS validation', detail:'Client certificates are checked at the router — PGD Proxy or the Connection Manager — before reaching any node.'},
        {label:'Zero-downtime rotation', detail:'Overlap old and new certificate validity windows; no restart needed.'},
        {label:'Community vs native', detail:'Some deployments still front the cluster with HAProxy instead of native routing.'}
      ],
      an:'The front desk checks ID before letting anyone through, and can swap to a new ID-checking policy without ever closing the lobby.',
      re:'Client <b>TLS certificates</b> are validated at the router — <b>PGD Proxy</b> or the <b>Connection Manager</b> — before a connection reaches any node. Certificates can be <b>rotated live</b> by overlapping old and new validity windows, for <b>zero downtime</b>. Some deployments still front the cluster with community <b>HAProxy</b> instead of native routing.',
      nr:'Client TLS certificates are validated at the router, whether that is PGD Proxy or the Connection Manager, before a connection ever reaches a node. Certificates can be rotated on a live cluster by overlapping the old and new certificate validity windows, so there is zero downtime. Some deployments still front the cluster with community HAProxy instead of the native routing layer.',
      bv:[['bdr.stat_connection_manager','connection totals per routing layer (v6)'],['bdr.node_config_summary','TLS-related configuration per node']]},
  ]}
);
